version: '3.8'
services:
  sandbox:
    build: gmod-server-docker
    ports:
      - 27015:27015/udp
    volumes:
      - ./write/sandbox:/gmod/write
      - ./instance/sandbox:/gmod/instance
      - ./common:/gmod/common
    privileged: true
    tty: true
    stop_grace_period: 30s
    environment:
      PORT: 27015
      MAP: gm_construct
  melonbomber:
    build: gmod-server-docker
    ports:
      - 27016:27016/udp
    volumes:
      - ./write/melonbomber:/gmod/write
      - ./instance/melonbomber:/gmod/instance
      - ./common:/gmod/common
    privileged: true
    tty: true
    stop_grace_period: 30s
    environment:
      PORT: 27016
      MAP: mb_melonbomber
      GAMEMODE: melonbomber
      WORKSHOP: 1489511514
