version: '3.8'
services:
  rethinkdb:
    image: rethinkdb
    hostname: rethinkdb
    ports: 127.0.0.1:8080:8080
  rethinkdb_setup:
    build: rethinkdb_setup
    environment:
      DATABASE_HOST: rethinkdb
  gmod_database_webserver:
    build: gmod-database-webserver
    environment:
      DATABASE_HOST: rethinkdb
    depends_on:
      - rethinkdb
  sandbox:
    build: gmod-server-docker
    ports:
      - 27015:27015/udp
    volumes:
      - ./write/sandbox:/gmod/write
      - ./instance/sandbox:/gmod/instance
      - ./common:/gmod/common
    privileged: true
    stop_grace_period: 30s
    environment:
      PORT: 27015
      MAP: gm_construct
      STEAM_SERVER_KEY: sandbox
    secrets:
      - steam_server_key
    depends_on:
      - gmod_database_webserver
  melonbomber:
    build: gmod-server-docker
    ports:
      - 27016:27016/udp
    volumes:
      - ./write/melonbomber:/gmod/write
      - ./instance/melonbomber:/gmod/instance
      - ./common:/gmod/common
    privileged: true
    stop_grace_period: 30s
    environment:
      PORT: 27016
      MAP: mb_melonbomber
      GAMEMODE: melonbomber
      WORKSHOP: 1489511514
      STEAM_SERVER_KEY: melonbomber
    secrets:
      - steam_server_key
    depends_on:
      - gmod_database_webserver
secrets:
  steam_server_key:
    file: ./secrets/steam_server_key.json
