version: '3.8'
services:
  sandbox:
    build: garrysmod
    ports:
      - 27015:27015/udp
    volumes:
      - ./instances/sandbox:/gmod/specific
      - ./common:/gmod/common
    privileged: true
    environment:
      PORT: 27015
      MAP: gm_construct
